package com.tenpo.tenpochallenge.infrastructure.persistence.repository;

import com.tenpo.tenpochallenge.domain.model.CallRecord;
import com.tenpo.tenpochallenge.domain.ports.CallRecordRepository;
import com.tenpo.tenpochallenge.infrastructure.persistence.entity.CallRecordEntity;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Repository;

/**
 * Adapter that implements the CallRecordRepository port using JPA
 */
@Repository
public class CallRecordRepositoryAdapter implements CallRecordRepository {
    
    private final JpaCallRecordRepository jpaRepository;
    
    public CallRecordRepositoryAdapter(JpaCallRecordRepository jpaRepository) {
        this.jpaRepository = jpaRepository;
    }
    
    @Override
    public CallRecord save(CallRecord callRecord) {
        CallRecordEntity entity = toEntity(callRecord);
        CallRecordEntity savedEntity = jpaRepository.save(entity);
        return toModel(savedEntity);
    }
    
    @Override
    public Page<CallRecord> findAll(Pageable pageable) {
        Page<CallRecordEntity> entities = jpaRepository.findAllByOrderByTimestampDesc(pageable);
        return entities.map(this::toModel);
    }
    
    private CallRecordEntity toEntity(CallRecord model) {
        CallRecordEntity entity = new CallRecordEntity(
                model.getTimestamp(),
                model.getEndpoint(),
                model.getRequestParams(),
                model.getResponse(),
                model.getErrorMessage(),
                model.getStatusCode()
        );
        
        if (model.getId() != null) {
            entity.setId(model.getId());
        }
        
        return entity;
    }
    
    private CallRecord toModel(CallRecordEntity entity) {
        // Using the Builder pattern generated by Lombok
        CallRecord model = CallRecord.builder()
                .id(entity.getId())
                .timestamp(entity.getTimestamp())
                .endpoint(entity.getEndpoint())
                .requestParams(entity.getRequestParams())
                .response(entity.getResponse())
                .errorMessage(entity.getErrorMessage())
                .statusCode(entity.getStatusCode())
                .isError(entity.getErrorMessage() != null && !entity.getErrorMessage().isEmpty())
                .build();
        
        return model;
    }
}
